version: '3.8'

services:
  php-stack:
    image: docker.io/sockee/php-stack
    ports:
      - "8080:80"
      - "9001:22"
      - "3306:3306"
    volumes: 
      - ./joomla-cms:/www/joomla_save
      - ./joomla-pr:/www/mediahelper_security
      - ./mysql:/opt/lampp/var/mysql/save_db
      - ./mysql:/opt/lampp/var/mysql/pr_db


